dataset_and_model:
  _target_: dataset_and_model.imagenet.get_dataset_and_model
  data_path: datasets/imagenet
  num_pics: 30
  model_path: None
  model_type: inceptionv3   #VIT

num_classes: 1000
image_size: 299
num_channels: 3
k: 10 #
spd: 32
epsilon: 0.1
batch_delta_size: 2
filterSize: 13
stride: 13

name: imagenet
eta: 0.01

grad_norm_threshold: 500
#VT group 14 nonoverlap