defaults:
  - dataset_and_model: cifar10
  - setup: default
  - scheduler: losslr
  
log_iters: 10000000000
gpu_idx: 0
parallel_device_num: 1
attack_all_pixels: False
save_image: False
save_result: False
load_pre_groups: True
max_iters: 1000
max_query: 20000
targeted: untargeted
subspace_dim: 2
alpha: 0.5
using_subspace: False

initial_delta: random

wandb: False
project: lr_scheduler
name: ${dataset_and_model.name}_${scheduler.name}
entity: yura1213

