defaults:
  - dataset_and_model: imagenet
  - setup: default


epoch: 64
warmup_epoch: 5
use_amp: True
train_update_steps: 16
test_update_steps: 16
tbptt_steps: 4
checkpoint_interval: 20
lr: 0.01
targeted: untargeted
max_batch_forward: 4

# if using margin_loss + regular term, set the eta
attack_loss_fun: cross_entropy_loss
penalty_fun: l2_regular_loss
penalty_eta: 0.1


gpu_idx: 3
project: DNN attack-Train l2l
entity: yura1213